"""add match_id and player_id to submissions

Revision ID: 3631e687b643
Revises: 2176c114cb66
Create Date: 2026-09-05 18:37:38.887343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3631e687b643'
down_revision: Union[str, Sequence[str], None] = '2176c114cb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('match_id', sa.UUID(), nullable=True))
    op.add_column('submissions', sa.Column('player_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'submissions', 'matches', ['match_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'player_id')
    op.drop_column('submissions', 'match_id')
    # ### end Alembic commands ###
