"""add player ratings and match rating audit fields

Revision ID: c389cd8a1941
Revises: f76af37bafe6
Create Date: 2026-09-05 19:07:55.623295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c389cd8a1941'
down_revision: Union[str, Sequence[str], None] = 'f76af37bafe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_ratings',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.add_column('matches', sa.Column('winner_rating_before', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('winner_rating_after', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('loser_rating_before', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('loser_rating_after', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'loser_rating_after')
    op.drop_column('matches', 'loser_rating_before')
    op.drop_column('matches', 'winner_rating_after')
    op.drop_column('matches', 'winner_rating_before')
    op.drop_table('player_ratings')
    # ### end Alembic commands ###
