"""add winner_id to matches

Revision ID: f76af37bafe6
Revises: 3631e687b643
Create Date: 2026-09-05 18:52:21.724580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76af37bafe6'
down_revision: Union[str, Sequence[str], None] = '3631e687b643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('winner_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'winner_id')
    # ### end Alembic commands ###
